### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/infografia-de-hilos-Azucena-Tejeda#2]
[INFOGRAFIA HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Azucena-Tejeda/files/6469124/INFOGRAFIA.HILOS.pdf)

**Comment by javiern-778** [comment]
19 un excelente trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
